from __future__ import annotations

from enum import StrEnum


class AssetType(StrEnum):
    COMMON_STOCK = "COMMON_STOCK"
    ETF = "ETF"


class SessionType(StrEnum):
    REGULAR = "REGULAR"
    PRE = "PRE"
    POST = "POST"


class EarningsEventSession(StrEnum):
    PRE_OPEN = "PRE_OPEN"
    POST_CLOSE = "POST_CLOSE"
    UNKNOWN = "UNKNOWN"


class RegimeState(StrEnum):
    RISK_ON = "RISK_ON"
    CAUTION = "CAUTION"
    RISK_OFF = "RISK_OFF"
    PANIC_REBOUND = "PANIC_REBOUND"


class SymbolLifecycleState(StrEnum):
    INELIGIBLE = "INELIGIBLE"
    ELIGIBLE = "ELIGIBLE"
    CANDIDATE = "CANDIDATE"
    ARMED = "ARMED"
    PENDING_ENTRY = "PENDING_ENTRY"
    ACTIVE = "ACTIVE"
    EXIT_PENDING = "EXIT_PENDING"
    CLOSED = "CLOSED"


class PatternType(StrEnum):
    PULLBACK = "PULLBACK"
    TIGHT_BASE = "TIGHT_BASE"


class OrderSide(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class OrderReason(StrEnum):
    ENTRY = "ENTRY"
    INITIAL_STOP = "INITIAL_STOP"
    TRAIL_STOP = "TRAIL_STOP"
    TIME_EXIT = "TIME_EXIT"
    EARNINGS_EXIT = "EARNINGS_EXIT"
    REGIME_EXIT = "REGIME_EXIT"
    KILL_SWITCH = "KILL_SWITCH"


class OrderType(StrEnum):
    MARKET = "MARKET"
    LIMIT = "LIMIT"
    STOP = "STOP"
    STOP_LIMIT = "STOP_LIMIT"


class ChartOHLCSeries(StrEnum):
    SPLIT_ADJUSTED = "SPLIT_ADJUSTED"


class ReturnCloseSeries(StrEnum):
    TOTAL_RETURN_CLOSE_INDEX = "TOTAL_RETURN_CLOSE_INDEX"


class ExecutionOHLCSeries(StrEnum):
    RAW = "RAW"


class BenchmarkTrendSeries(StrEnum):
    SPLIT_ADJUSTED_CLOSE = "SPLIT_ADJUSTED_CLOSE"


class BenchmarkRealizedVolSeries(StrEnum):
    TOTAL_RETURN_CLOSE_INDEX = "TOTAL_RETURN_CLOSE_INDEX"


class RealizedVolMethod(StrEnum):
    ANNUALIZED_STD_LOG_RETURNS = "ANNUALIZED_STD_LOG_RETURNS"


class SourceUniverse(StrEnum):
    STRATEGY_COMMON_STOCK_UNIVERSE_PIT = "STRATEGY_COMMON_STOCK_UNIVERSE_PIT"


class NormalizationMethod(StrEnum):
    CROSS_SECTIONAL_ZSCORE = "CROSS_SECTIONAL_ZSCORE"


class TrendQualityFormula(StrEnum):
    LINEAR_CLAMPED_V1 = "LINEAR_CLAMPED_V1"


class SubmissionTiming(StrEnum):
    AFTER_SIGNAL_CLOSE_FOR_NEXT_REGULAR_SESSION = "AFTER_SIGNAL_CLOSE_FOR_NEXT_REGULAR_SESSION"


class OpeningPrintReference(StrEnum):
    PRIMARY_EXCHANGE_OFFICIAL_OPEN = "PRIMARY_EXCHANGE_OFFICIAL_OPEN"


class RegimeExitMode(StrEnum):
    TIGHTEN_TRAILING_STOP_ONLY = "TIGHTEN_TRAILING_STOP_ONLY"


class BrokerName(StrEnum):
    PAPER = "PAPER"


class RuntimeMode(StrEnum):
    PAPER = "PAPER"
    SHADOW = "SHADOW"


class ReviewStatus(StrEnum):
    PASS = "PASS"
    WARN = "WARN"
    FAIL = "FAIL"


class RuntimeEventType(StrEnum):
    PENDING_ENTRY_ACTION_DECIDED = "PENDING_ENTRY_ACTION_DECIDED"
    PAPER_ENTRY_SUBMISSION_DECIDED = "PAPER_ENTRY_SUBMISSION_DECIDED"
    SHADOW_ENTRY_PROPOSAL_DECIDED = "SHADOW_ENTRY_PROPOSAL_DECIDED"
    SHADOW_FILL_COMPARISON_RECORDED = "SHADOW_FILL_COMPARISON_RECORDED"
    RUNTIME_CYCLE_RESULT_WRITTEN = "RUNTIME_CYCLE_RESULT_WRITTEN"
    SHADOW_COMPARISON_WRITTEN = "SHADOW_COMPARISON_WRITTEN"
    SHADOW_SUMMARY_WRITTEN = "SHADOW_SUMMARY_WRITTEN"
    PAPER_SHADOW_AUDIT_SUMMARY_WRITTEN = "PAPER_SHADOW_AUDIT_SUMMARY_WRITTEN"
    AUDIT_REPORT_WRITTEN = "AUDIT_REPORT_WRITTEN"
    REVIEW_REPORT_WRITTEN = "REVIEW_REPORT_WRITTEN"
    HISTORICAL_REPLAY_WRITTEN = "HISTORICAL_REPLAY_WRITTEN"
    WORKFLOW_SUMMARY_WRITTEN = "WORKFLOW_SUMMARY_WRITTEN"


class ShadowFillStatus(StrEnum):
    FILLED = "FILLED"
    UNFILLED = "UNFILLED"
    OPEN_GAP_CANCELLED = "OPEN_GAP_CANCELLED"
    MISSING_MARKET_DATA = "MISSING_MARKET_DATA"


class PaperShadowAlignmentStatus(StrEnum):
    ALIGNED_FILLED = "ALIGNED_FILLED"
    ALIGNED_NOT_FILLED = "ALIGNED_NOT_FILLED"
    SHADOW_ONLY = "SHADOW_ONLY"
    PAPER_ONLY = "PAPER_ONLY"
    SHADOW_FILLED_PAPER_NOT_FILLED = "SHADOW_FILLED_PAPER_NOT_FILLED"
    SHADOW_NOT_FILLED_PAPER_FILLED = "SHADOW_NOT_FILLED_PAPER_FILLED"


class PendingEntryCancelReason(StrEnum):
    OPEN_GAP_ABOVE_LIMIT = "OPEN_GAP_ABOVE_LIMIT"
    EXPIRED = "EXPIRED"
    REGIME_BLOCKED = "REGIME_BLOCKED"
    EARNINGS_WINDOW_BREACHED = "EARNINGS_WINDOW_BREACHED"
    SHARED_PRECONDITIONS_FAILED = "SHARED_PRECONDITIONS_FAILED"
    INTENT_INVALIDATED = "INTENT_INVALIDATED"


class OrderIntentStatus(StrEnum):
    GENERATED = "GENERATED"
    ACTIVE = "ACTIVE"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class BrokerOrderStatus(StrEnum):
    OPEN = "OPEN"
    FILLED = "FILLED"
    CANCELLED = "CANCELLED"
    REJECTED = "REJECTED"
    EXPIRED = "EXPIRED"


class AlertSeverity(StrEnum):
    INFO = "INFO"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"


class MonitoringAlertType(StrEnum):
    STALE_DATA = "STALE_DATA"
    SLIPPAGE = "SLIPPAGE"
    DRAWDOWN_KILL_SWITCH = "DRAWDOWN_KILL_SWITCH"
    RECONCILIATION_MISMATCH = "RECONCILIATION_MISMATCH"
    BROKER_UNAVAILABLE = "BROKER_UNAVAILABLE"
